# Generated by Django 3.1.3 on 2020-11-11 12:56

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0002_auto_20201108_1442'),
    ]

    operations = [
        migrations.AddField(
            model_name='weather',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 11, 12, 56, 7, 253715, tzinfo=utc), verbose_name='date requested'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='weather',
            name='city',
            field=models.CharField(max_length=200),
        ),
        migrations.DeleteModel(
            name='CityRequest',
        ),
    ]
