# Generated by Django 3.1.3 on 2020-11-11 19:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0003_auto_20201111_1456'),
    ]

    operations = [
        migrations.CreateModel(
            name='CityReq',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=50)),
                ('date', models.DateTimeField(verbose_name='date requested')),
            ],
        ),
        migrations.AlterField(
            model_name='weather',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weather.cityreq'),
        ),
    ]
