# Generated by Django 3.1.3 on 2020-11-11 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0004_auto_20201111_2152'),
    ]

    operations = [
        migrations.RenameField(
            model_name='weather',
            old_name='city',
            new_name='city_name',
        ),
    ]
