# Generated by Django 3.1.3 on 2020-11-11 20:34

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0005_auto_20201111_2202'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cityreq',
            name='date',
        ),
        migrations.AlterField(
            model_name='weather',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 11, 20, 34, 31, 199099, tzinfo=utc), verbose_name='date requested'),
        ),
    ]
