# Generated by Django 3.1.3 on 2020-11-12 12:53

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0006_auto_20201111_2234'),
    ]

    operations = [
        migrations.AddField(
            model_name='weather',
            name='icon',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='weather',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 12, 12, 53, 41, 736665, tzinfo=utc), verbose_name='date requested'),
        ),
    ]
