# Generated by Django 3.1.3 on 2020-11-12 12:54

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0007_auto_20201112_1453'),
    ]

    operations = [
        migrations.AddField(
            model_name='cityreq',
            name='code',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='weather',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 12, 12, 54, 34, 257386, tzinfo=utc), verbose_name='date requested'),
        ),
    ]
