# Generated by Django 3.1.3 on 2020-11-12 12:54

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0008_auto_20201112_1454'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cityreq',
            old_name='code',
            new_name='cod',
        ),
        migrations.AlterField(
            model_name='weather',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 12, 12, 54, 44, 996403, tzinfo=utc), verbose_name='date requested'),
        ),
    ]
