# Generated by Django 3.1.3 on 2020-11-12 13:38

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0009_auto_20201112_1454'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cityreq',
            name='cod',
        ),
        migrations.AddField(
            model_name='weather',
            name='cod',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='weather',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 12, 13, 38, 9, 477549, tzinfo=utc), verbose_name='date requested'),
        ),
    ]
