# Generated by Django 3.1.3 on 2020-11-16 19:43

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0011_auto_20201113_1525'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='DateFrom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_from', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='DateTo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_to', models.DateTimeField()),
            ],
        ),
        migrations.AlterField(
            model_name='weather',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 16, 19, 43, 32, 865132, tzinfo=utc), verbose_name='date requested'),
        ),
        migrations.AlterField(
            model_name='weather',
            name='description',
            field=models.CharField(default='', max_length=200),
        ),
    ]
