# Generated by Django 3.1.3 on 2020-11-17 11:32

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0012_auto_20201116_2143'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoryReq',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_to', models.DateTimeField(default=datetime.datetime(2020, 11, 17, 11, 32, 30, 844982, tzinfo=utc))),
                ('date_from', models.DateTimeField(default=datetime.datetime(2020, 10, 17, 11, 24, 32))),
                ('city', models.CharField(default='Nan', max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='City',
        ),
        migrations.DeleteModel(
            name='DateFrom',
        ),
        migrations.DeleteModel(
            name='DateTo',
        ),
        migrations.AlterField(
            model_name='weather',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 17, 11, 32, 30, 844982, tzinfo=utc), verbose_name='date requested'),
        ),
    ]
