# Generated by Django 3.1.3 on 2020-11-17 11:35

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0013_auto_20201117_1332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historyreq',
            name='city',
            field=models.CharField(default='All', max_length=20),
        ),
        migrations.AlterField(
            model_name='historyreq',
            name='date_to',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 17, 11, 35, 0, 696768, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='weather',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 17, 11, 35, 0, 696768, tzinfo=utc), verbose_name='date requested'),
        ),
    ]
