# Generated by Django 3.1.3 on 2020-11-18 12:38

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0014_auto_20201117_1335'),
    ]

    operations = [
        migrations.CreateModel(
            name='CityWeather',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(max_length=2)),
                ('date', models.DateTimeField(default=datetime.datetime(2020, 11, 18, 12, 38, 9, 438049, tzinfo=utc), verbose_name='date requested')),
                ('temp', models.FloatField(default=0)),
                ('description', models.CharField(default='', max_length=200)),
                ('icon', models.CharField(default='', max_length=10)),
                ('cod', models.IntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='weather',
            name='city_name',
        ),
        migrations.AlterField(
            model_name='historyreq',
            name='date_to',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 18, 12, 38, 9, 494944, tzinfo=utc)),
        ),
        migrations.DeleteModel(
            name='CityReq',
        ),
        migrations.DeleteModel(
            name='Weather',
        ),
    ]
