# Generated by Django 3.1.3 on 2020-11-18 12:40

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0015_auto_20201118_1438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cityweather',
            name='city_name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='cityweather',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 18, 12, 40, 34, 505683, tzinfo=utc), verbose_name='date requested'),
        ),
        migrations.AlterField(
            model_name='historyreq',
            name='date_to',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 18, 12, 40, 34, 555788, tzinfo=utc)),
        ),
    ]
