# Generated by Django 3.1.3 on 2020-11-27 15:26

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0025_auto_20201127_1714'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cityweather',
            name='date',
        ),
        migrations.AddField(
            model_name='city',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 27, 15, 26, 4, 825539, tzinfo=utc), verbose_name='date requested'),
        ),
        migrations.AlterField(
            model_name='historyreq',
            name='date_to',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 27, 15, 26, 4, 875361, tzinfo=utc)),
        ),
    ]
