# Generated by Django 3.1.3 on 2020-11-27 15:48

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0027_auto_20201127_1731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cityweather',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 27, 15, 48, 48, 622669, tzinfo=utc), verbose_name='date requested'),
        ),
        migrations.AlterField(
            model_name='historyreq',
            name='date_to',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 27, 15, 48, 48, 622669, tzinfo=utc)),
        ),
    ]
