# Generated by Django 3.1.3 on 2020-11-27 16:01

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0029_auto_20201127_1750'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='cod',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='cityweather',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 27, 16, 1, 38, 679332, tzinfo=utc), verbose_name='date requested'),
        ),
        migrations.AlterField(
            model_name='historyreq',
            name='date_to',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 27, 16, 1, 38, 680364, tzinfo=utc)),
        ),
    ]
