# Generated by Django 3.1.3 on 2020-11-28 10:30

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0037_auto_20201128_1221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historyreq',
            name='date_to',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 28, 10, 30, 50, 372568, tzinfo=utc)),
        ),
        migrations.DeleteModel(
            name='CityWeather',
        ),
    ]
