# Generated by Django 3.1.3 on 2020-11-28 11:47

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0042_auto_20201128_1344'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CityWeather',
        ),
        migrations.AlterField(
            model_name='historyreq',
            name='date_to',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 28, 11, 47, 22, 530039, tzinfo=utc)),
        ),
    ]
