# Generated by Django 3.1.3 on 2020-11-28 11:48

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0043_auto_20201128_1347'),
    ]

    operations = [
        migrations.CreateModel(
            name='CityWeather',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(max_length=20)),
                ('temp', models.FloatField(default=0)),
                ('date', models.DateTimeField(default=datetime.datetime(2020, 11, 28, 11, 48, 20, 988408, tzinfo=utc), verbose_name='date requested')),
                ('description', models.CharField(default='', max_length=200)),
                ('icon', models.CharField(default='', max_length=10)),
                ('cod', models.IntegerField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='historyreq',
            name='date_to',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 28, 11, 48, 21, 38989, tzinfo=utc)),
        ),
    ]
